server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: auth-service

  rest:
    template:
      connect-timeout: 3s
      read-timeout: 5s

jwt:
  secret: ${JWT_SECRET:dKLyb0ao3/f8ZlQ2CVJc9Auhz3VdaBo8NSnOxbA/8Kc=}
  expiration: ${JWT_EXPIRATION:3600000}
  issuer: ${JWT_ISSUER:capbank-gateway}
