server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: bankaccount-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_bankaccount}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      continue-on-error: true
      platform: h2

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: true

app:
  database:
    postgresql:
      version: 15

  gateway:
    base-url: ${GATEWAY_BASE_URL:http://localhost:8081}

  rest:
    template:
      connect-timeout: 3s
      read-timeout: 5s