services:
  
  # BANCO DE DADOS POSTGRESQL
  db_capbank:
    image: postgres:16-alpine
    container_name: db_capbank
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data/auth:/var/lib/postgresql/data
      - ./data/postgres-init:/docker-entrypoint-initdb.d
    networks:
      - capbank_network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  # MICROSERVIÇOS

networks:
  capbank_network:
    driver: bridge