server:
  port: 8083
  servlet:
    context-path: /transaction-service

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://localhost:5432/capbank_transactions
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false

# Logging Configuration
logging:
  level:
    com.capbank.transaction_service: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
  info:
    title: Transaction History Service API
    description: API para gerenciamento de histórico de transações bancárias
    version: 1.0.0
    contact:
      name: Capbank Team
      email: team@capbank.com

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true
    java:
      enabled: true
    build:
      enabled: true

# Application Info
info:
  app:
    name: Transaction History Service
    description: Microservice for managing transaction history
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 17