server:
  port: 8081

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-login-proxy
          uri: ${services.auth.base-url:http://localhost:8083}
          predicates:
            - Path=/api/user/login
          filters:
            - SetPath=/api/auth/login
            - name: CircuitBreaker
              args:
                name: authCircuit
                fallbackUri: forward:/fallback/service-unavailable
        - id: user-service
          uri: ${services.user.base-url:http://localhost:8082}
          predicates:
            - Path=/api/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: userCircuit
                fallbackUri: forward:/fallback/service-unavailable
        - id: auth-service
          uri: ${services.auth.base-url:http://localhost:8083}
          predicates:
            - Path=/api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuit
                fallbackUri: forward:/fallback/service-unavailable
        - id: account-service
          uri: ${services.account.base-url:http://localhost:8084}
          predicates:
            - Path=/api/bankaccount/**
          filters:
            - name: CircuitBreaker
              args:
                name: accountCircuit
                fallbackUri: forward:/fallback/service-unavailable
        - id: transaction-service
          uri: ${services.transaction.base-url:http://localhost:8085}
          predicates:
            - Path=/api/transaction/**
          filters:
            - name: CircuitBreaker
              args:
                name: transactionCircuit
                fallbackUri: forward:/fallback/service-unavailable
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

jwt:
  secret: VGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkhIQ==

services:
  auth:
    base-url: ${AUTH_SERVICE_BASE_URL:http://localhost:8083}
  user:
    base-url: ${USER_SERVICE_BASE_URL:http://localhost:8082}
  account:
    base-url: ${ACCOUNT_SERVICE_BASE_URL:http://localhost:8084}
  transaction:
    base-url: ${TRANSACTION_SERVICE_BASE_URL:http://localhost:8085}
