server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
     url: jdbc:postgresql://localhost:5432/db_user
     username: postgres
     password: postgres
     driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      continue-on-error: true
      platform: h2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  database:
    postgresql:
      version: 16

  rest:
    template:
      connect-timeout: 3s
      read-timeout: 5s